possible_values = {
    "__loc": ["paris", "london", "tokyo", "Honolulu", "Berlin",
              "Miami", "Stockholm", "Beirut", "Rome", "France",
              "Italie", "Germany"],
    "__num": ["1", "2", "3", "4", "5"],
    "__pers": ["Bob", "Brian", "Alice", "Jack", "Joe",
               "Bill", "Robert"],
    "__date": ["Friday", "Monday", "Sunday", "Tuesday",
               "Wednesday", "Thursday", "Saturday"],
    "__var": ["table", "chair", "apple", "bird", "bakery",
              "plan", "train", "dog", "wheelchair", "car",
              "orange","meal", "friendship", "suitcase", "bike",
              "tree", "vegatable", 'spider'],
    "__search": ["wikipedia", "dictionnary", "web"],
    "__device": ["light", "alarm", "television"]
}

data = [
    {"patterns": ["search for __var1",
                  "search the definition of __var1",
                  "show me the definition of __var1",
                  "what's a __var1 ?",
                  "do you know what is a __var1",
                  "search for __var1",
                  "What does a __var1 mean",
                  "what is the definition of __var1"],
     "domains": ["search"]},
    {"patterns": ["open __search1",
                  "go to __search1",
                  "Open __search1 website"], "domains": ["search"]},
    {"patterns": ["send a new mail to __pers1",
                  "send an email to __pers1",
                  "Can you send an email to __pers1"],
     "domains": ["mail"]},
    {"patterns": ["set the subject of the email to __var1",
                  "set the subject to __var1",
                  "Write __var1 as the subject of the email"],
     "domains": ["mail"]},
    {"patterns": ["send the draft",
                  "ok, now send the draft",
                  "Press the send button"],
     "domains": ["mail"]},
    {"patterns": ["close the inbox tab",
                  "Thanks now you can close the inbox tab"],
     "domains": ["mail"]},
    {"patterns": ["create an email with __pers1 as recipient about __var1 and send him its __search1 definition",
                  "Prepare an email for __pers1 with the definition from __search1 of __var1",
                  "Get the definition of __var1 on __search1 and write a mail about it to __pers1",
                  "send the definition from __search1  of __var1 to __pers1",
                  "tell the definition you find on __search1 of __var1 to __pers1"],
     "domains": ["mail", "search"]},
    {"patterns": ["set the contents with __var1",
                  "write __var1 in the the contents",
                  "Put __var1 in the contents"],
     "domains": ["mail"]},
    {"patterns": ["send the email",
                  "send the email through Inbox"],
     "domains": ["mail"]},
    {"patterns": ["close __search1",
                  "please close the __search1 tab"],
     "domains": ["search"]},
    {"patterns": ["create a mail draft",
                  "can you create a draft please",
                  "create a new draft",
                  "go to inbox and create a draft"],
     "domains": ["mail"]},

    {"patterns": ["set the recipient with __pers1",
                  "fill the recipient of the message __pers1",
                  "this mail is for __pers1"],
     "domains": ["mail"]},
    {"patterns": ["put it in my message and send the message to __pers1",
                  "Write it in my message and send the mail to __pers1",
                  "Can you add it to my mail and send it to __pers1"],
     "domains": ["mail"]},

    {"patterns": ["can you buy __num1 tickets",
                  "buy __num1 concert tickets", "Can you book __num1 tickets",
                  "I need __num1 tickets"],
     "domains": ["ticket"]},
    {"patterns": ["buy __num1 tickets for the __pers1 concert",
                  "there is the __pers1 concert soon, can you buy __num1 tickets for me",
                  "Get me __num1 tickets for __pers1 concert"],
     "domains": ["ticket"]},
    {"patterns": ["exchange my __num1 tickets for a refund",
                  "can you refund and buy another __num1 tickets",
                  "I need to cancel my booking for __num1 tickets"],
     "domains": ["ticket"]},
    {"patterns": ["swap my __num1 tickets for __pers1 with the __pers2 concert",
                  "please, refund my __num1 tickets for the __pers1 concert and buy new tickets for the __pers2 concert",
                  "I change my plan and need to exchange __num1 tickets for __pers1 concert for tickets for the concert of __pers2",
                  "Can you switch the __num1 tickets for __pers1 concert for tickets for __pers2 concert "],
     "domains": ["ticket"]},
    {"patterns": ["Can you ask __pers1 if he would be interested in the tickets for __pers2 concert",
                  "Message __pers1 about the tickets for __pers2 concert"],
     "domains": ["ticket", "mail"]},
    {"patterns": ["Can you ask __pers1 if he would be interested in the tickets for __pers2 concert on __date1",
                  "Message __pers1 about the tickets for __pers2 concert on __date1"],
     "domains": ["ticket", "mail"]},

    {"patterns": ["search __pers1 on __search1 then buy a ticket for his concert",
                  "check on __search1 for __pers1 and then try to buy a ticket for his concert"],
     "domains": ["ticket", "search"]},
    {"patterns": ["Check my calendar and then buy a ticket for __pers1 concert",
                  "If I am available, can you get me a ticket for __pers1 concert"],
     "domains": ["ticket", "calendar"]},
    {"patterns": [
        "can you buy __num1 tickets for __pers1 concert, then write an email to __pers2 and tell him that I bought tickets for __pers1 concert",
        "buy __num1 tickets for __pers1 concert, then send an email to __pers2 saying that I bought tickets for the __pers1 concert ",
        "Please book __num1 tickets for  __pers1 concert and tell __pers2 about it"],
        "domains": ["ticket", "mail"]},
    {"patterns": ["buy __num1 tickets for the __date1 night and add the corresponding concert event to my calendar",
                  "please, buy __num1 tickets for __date1 then save the event in my calendar",
                  "Can you book __num1 tickets for __date1 and put a reminder in my calendar"],
     "domains": ["ticket", "calendar"]},

    {"patterns": ["when do I have a meeting with __pers1", "what day do I have a meeting with __pers1",
                  "when do I meet __pers1"], "domains": ["calendar"]},

    {"patterns": ["set a meeting with __pers1 on __date1", "I will meet with __pers1 on __date1",
                  "set me a meeting on __date1 with __pers1"],
     "domains": ["calendar"]},
    {"patterns": ["when do I go to __loc1", "what day do I go to __loc1", "when am I supposed to go to __loc1"],
     "domains": ["calendar"]},
    {"patterns": ["who is coming to the meeting on __date1", "who will be at the meeting on __date1",
                  "who is planning to attend the meeting on __date1"], "domains": ["calendar"]},
    {"patterns": ["look for flights from __loc1 to __loc2", "find me a flight from __loc1 to __loc2",
                  "get me a flight from __loc1 to __loc2", 'what are the flights from __loc1 to __loc2'],
     "domains": ["travel"]},
    {"patterns": ["should I set it on __date1 or __date2", "According to my calendar, is __date1 or __date2 better",
                  "What is better between __date1 and __date2", "Would you recommend __date1 or __date2"],
     "domains": ["calendar"]},

    {"patterns": ["I want to go on __date1",
                  "The trip is on __date1",
                  "I will go on __date1"],
     "domains": ["travel"]},

    {"patterns": ["how far is it from __loc1 to __loc2",
                  "what is the distance from __loc1 to __loc2",
                  "how far is __loc1 from __loc2"],
     "domains": ["travel"]},
    {"patterns": ["Get me the price for ticket from __loc1 to __loc2",
                  "What is the price for a ticket from __loc1 to __loc2",
                  "How much does the ticket from __loc1 to __loc2 cost",
                  "how much does it cost to travel from __loc1 to __loc2"],
     "domains": ["travel"]},
    {"patterns": ["Get me the price for ticket from __loc1 to __loc2 on __date1",
                  "What is the price for a ticket from __loc1 to __loc2 on __date1",
                  "On __date1 how much does it cost to travel from __loc1 to __loc2"],
     "domains": ["travel"]},
    {"patterns": ["Remind __pers1 of our meeting on __date1",
                  "Can you remind __pers1 of our meeting on __date1",
                  "Please send a reminder to __pers1 about our meeting on __date1"],
     "domains": ["mail", "calendar"]},
    {"patterns": ["Is there an airport in __loc1",
                  "Any airport in __loc1"],
     "domains": ["travel"]},
    {"patterns": ["When am I supposed to meet __pers1",
                  "When is my next meeting with __pers1",
                  "On what day is the meeting with __pers1",
                  "I cannot remember when is the meeting with __pers1 , look for it pleases"],
     "domains": ["calendar"]},
    {"patterns": ["I need to organise a meeting with __pers1 to talk about __var1",
                  "Plan a meeting with __pers1 about __var1"],
     "domains": ["calendar"]},
    {"patterns": ["Can you set a meeting with __pers1 to talk about __var1 project on __date1",
                  "I need to set a meeting with __pers1 to talk about __var1 project on __date1",
                  "Plan a meeting with __pers1 about __var1 on __date1"],
     "domains": ["calendar"]},
    {"patterns": ["how long is the trip from __loc1 to __loc2",
                  "how long is the trip between __loc1 to __loc2",
                  "Can you tell me how it will take to go from __loc1 to __loc2"],
     "domains": ["travel"]},
    {"patterns": ["Get me the price for a trip to __loc1 between __date1 and __date2",
                  "What is the price for a trip to __loc1 from __date1 to __date2",
                  "Between __date1 and __date2 how much does it cost to travel to __loc1"],
     "domains": ["search"]},
    {"patterns": ["How is the weather in __loc1 on __date1",
                  "Will the weather be fine in __loc1 on __date1"],
     "domains": ["search"]},
    {"patterns": ["Can you turn on the __device1 in my home in __loc1",
                  "Please make sure the __device1 is turned on at my house in __loc1",
                  "Switch on the __device1 in __loc1"],
     "domains": ["IoT"]},
    {"patterns": ["When __device1 is off, please turn on  __device2",
                  "Can you control that when __device1 is turned off, __device2 is turned on",
                  "I want that when __device1 is switched off, __device2 is automatically switched on",
                  "After you turn off __device1 , turn on __device2"],
     "domains": ["IoT"]},
    {"patterns": ["Add a reminder on my calendar on __date1 to repair __device1",
                  "Can you remind me to repair __device1 on __date1",
                  "I need to be reminded on __date1 that __device1 needs repairing"],
     "domains": ["IoT", "calendar"]},
    {"patterns": ["Can you set up the alarm on __date1",
                  "Please turn on the alarm on __date1",
                  "Switch on the alarm on __date1"],
     "domains": ["IoT"]},
    {"patterns": ["Make sure the __device1 is always off on __date1",
                  "Verify that __device1 is always off on __date1",
                  "I want __device1 off on __date1"],
     "domains": ["IoT"]},
    {"patterns": ["Always turn off __device1 before turning on __device2",
                  "__device1 needs to be off before __device2 is turned on"],
     "domains": ["IoT"]},
    {"patterns": ["Are you connected to __device1",
                  "Can you take control of __device1"],
     "domains": ["IoT"]},
    {"patterns": ["What is the status of __device1",
                  "Tell me the status of __device1",
                  "Is __device1 on or off"], "domains": ["IoT"]},
    {"patterns": ["Get me a report of __device1 usage on __date1",
                  "I want to know how __device1 was used on __date1",
                  "How was __device1 used on __date1"],
     "domains": ["IoT"]},

]


default_train_corpus = [
    ["can you buy a ticket", "please, buy a concert ticket for me", 1],
    ["can you buy a ticket", "close the inbox tab", 0]
]

if __name__ == '__main__':
    n_pattern = 0
    for i in data:
        n_pattern += len(i["patterns"])
    print(f'{len(data)} different intents and {n_pattern} different patterns')
